sudo: false
language: node_js
node_js:
- stable
before_install:
- source read.version.sh
- echo $PACKAGE_JSON_MAJOR_MINOR_VERSION
install:
- npm install
script:
- npm run build
- npm test
- npm run coveralls
after_success:
- mkdir deploy
- cp dist/coveoua.js dist/coveoua.js.map deploy
deploy:
- provider: npm
  skip_cleanup: true
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: "WJ3Q4PqHx4G+h5RT8Yfy+2Qte5ITwchSHdu8DHMv4c7JzWcEUYmwXlDnLGJtz96koN/gidQZxAQhSb/M2jEFU6+4OoVrUjxEh6Xuc1xUz5M9SfgDXeEW1EbXkY11UvWdetIGDg6Q+3x71q1eLGD377tR/VSc2pplqm0X1Aj8SZgAfUOtd2XLJvv/EbFVNCKXEkXghHdi9MdmWnRA96HP/nrWrMq2Cmde4tZhdY4gMlb2Vv/3xtw5MdUDXk2XjLxNCfU0LwfejF00+7112xbD7jzdCGro2ru63T+WqzWnA5zILLUltQSiH3xl7FMvhCk3i/tiwXQsQJuGtGK1ZW61daxE5tue+DWqUDDqpqoPac4LvoXcprJutpafHwiovY+NY/4tz++cPTiX9odaNDAs4PB7+3/f4WbjmQ7svjZ3u48mD5hCVbVLSCPPgu00NozSBhs3hGvQomoXoruLm2u4EZruVcKMpHzld6RYrYSLtWj4r8nmmYxgkPLk76Z871xh70MvaYdf23mWaDziUFOySt60M5OTlnrdg5CpX+n+qQkLQCs8QGdNDu6x2gNt1OkRc0J7kf4UI747dAsHNo5CLR4bUWZBe/olj2y6l17XhACHUpvwlyrfKS0XC0KRdLrdDqS/DBJfsKlLYh6SLsOFG/BdhpAx5iF7KXvrpEYqKM0="
  on:
    tags: true
    condition: "$TRAVIS_TAG != latest"
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ3KKKVUARABLBBDA
  secret_access_key:
    secure: "1QhM57Lhad0fmScPzq/N8BUfaV+8ITG3zc+7R5lqiN92+wKsh2qnU2urLyQKexoOyuhf9HENbwTj55wT5CYU4vhKKxFf6LA364CvvbmHkjuupZpJUCCJtWrm9riCLNG4+rFT86aj+m0VDoqAOJEqua+v8b+fY/ZHfiHvIynLYSe1gyQxitlC7ya5Qq3266bnDVx1b21S0CLmjSAQ0w4RpQof0IZTJ0OiLQ8moBNVCcU35GNSsveSd4uTwjWjzBhEq33jfB8/KFor/w9KM5u6am6DuXECRPDZwI7SGv//bmw5GG1K+m1DiXhJsGkimLPMqMRU11MP4RPzBCjv4f0/dy0+U8uAe+2QZMeS3MITB4/EL0b3bVzsZ1zgoR/8V3WT+DbMgc/SEFn0cmUWKnhVsR2fVCWzgX5osZVVtpwyLEKE35Q+9livKYlIrjlnQTAnc1LXMc3yVM/gj3y8wqeR9Z03RecZDgxsraiFoOkFM6H8AwDJARBzuCr8Dw+MxleJxg9H8r0UWXWipEHnzacwGSHRf4Q+uXAzJgbX4uyd1cfoPMx66W5VoauAmFgLicNa1CuziHB7gym52s/nWG1Wd92XiWGOD6WSkjWOq6sI1w9+8ka49xp4AxOegXwk9PO9icFPVnP3SoqG5S1Rn4PC/d2Me8wR1Y56y0FGJhXsu+I="
  bucket: coveo-public-content
  local-dir: dist
  upload-dir: coveo.analytics.js/$TRAVIS_TAG
  acl: public_read
  on:
    tags: true
    condition: "$TRAVIS_TAG != latest"
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ3KKKVUARABLBBDA
  secret_access_key:
    secure: "1QhM57Lhad0fmScPzq/N8BUfaV+8ITG3zc+7R5lqiN92+wKsh2qnU2urLyQKexoOyuhf9HENbwTj55wT5CYU4vhKKxFf6LA364CvvbmHkjuupZpJUCCJtWrm9riCLNG4+rFT86aj+m0VDoqAOJEqua+v8b+fY/ZHfiHvIynLYSe1gyQxitlC7ya5Qq3266bnDVx1b21S0CLmjSAQ0w4RpQof0IZTJ0OiLQ8moBNVCcU35GNSsveSd4uTwjWjzBhEq33jfB8/KFor/w9KM5u6am6DuXECRPDZwI7SGv//bmw5GG1K+m1DiXhJsGkimLPMqMRU11MP4RPzBCjv4f0/dy0+U8uAe+2QZMeS3MITB4/EL0b3bVzsZ1zgoR/8V3WT+DbMgc/SEFn0cmUWKnhVsR2fVCWzgX5osZVVtpwyLEKE35Q+9livKYlIrjlnQTAnc1LXMc3yVM/gj3y8wqeR9Z03RecZDgxsraiFoOkFM6H8AwDJARBzuCr8Dw+MxleJxg9H8r0UWXWipEHnzacwGSHRf4Q+uXAzJgbX4uyd1cfoPMx66W5VoauAmFgLicNa1CuziHB7gym52s/nWG1Wd92XiWGOD6WSkjWOq6sI1w9+8ka49xp4AxOegXwk9PO9icFPVnP3SoqG5S1Rn4PC/d2Me8wR1Y56y0FGJhXsu+I="
  bucket: coveo-public-content
  local-dir: deploy
  upload-dir: coveo.analytics.js/$PACKAGE_JSON_MAJOR_MINOR_VERSION
  acl: public_read
  on:
    tags: true
    condition: "$TRAVIS_TAG = latest"
    repo: coveo/coveo.analytics.js
notifications:
  email:
    on_success: never
    on_failure: never
