sudo: false
language: node_js
node_js:
- stable
install:
- npm install
- "$(npm bin)/typings install"
script:
- npm run build
- npm test
- npm run coveralls
after_success:
  - mkdir deploy
  - cp dist/coveoua.js dist/coveoua.js.map deploy
deploy:
- provider: npm
  skip_cleanup: true
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: "lsYaqqLuLJR3BGuvO4hqq7ptHX8QvMpyO0XdDATY7FWs35+CxeVe6GxYkX+rKOFNL0Cn4j+pi3kGbJS/3NkVvpU5+x7GldVBt04cQxrsmaE88rieJqQeYzGS9mKUyaxSk1G7Ty3NfMOi/izjWfjV5Mwt7EBXOsqwTbkGaXy0Ny3ysRnQK7LG1ZV1ZG0tJebKbk5a0zHjE8BLyARt9wQagEDQWIQF0JMIX/XYmjyh9UA8lxeovGOxxAtdtBeHijptBmA8AcqrHK4ZbgecLIFI4LxxGM7Gu1PTOaB+jcOVZgGgdLoS0frlRUXOTAnNt9pW9XteL8hrtcuPyNBdEXwMnrzxeGMOcZkClx7HM9hS0a9D8shZpOUQqd6pvxQmANhoQTIH9spNSocDQOzxN+F9TsiHA0+9fHebPIviqZ4JVx4T7tbrBDqaxlRSyvCHjvlRM0wwJZymrhHY0NAytdp590d2ub+IQe7PRdKjuctYeIhBCSWCc/oSyjp5yT6ZgQZnok/AHVS5UZipPo3/sjM1SPUSCU5KwzLWJgrrUQA6wenlUr0McAxL+BoXxcqz4F/8y05PCtbrrC2h0HstuI/X1DjMG4xpZ1zermAyFdGK69QkZ43q76u10rFNwcpmdn8y4xESX7enZLZN7gC4ZXPmc2/qFtRMTAPb1uUEYLaC3iQ="
  on:
    tags: true
    condition: "$TRAVIS_TAG != latest"
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ3KKKVUARABLBBDA
  secret_access_key:
    secure: "1QhM57Lhad0fmScPzq/N8BUfaV+8ITG3zc+7R5lqiN92+wKsh2qnU2urLyQKexoOyuhf9HENbwTj55wT5CYU4vhKKxFf6LA364CvvbmHkjuupZpJUCCJtWrm9riCLNG4+rFT86aj+m0VDoqAOJEqua+v8b+fY/ZHfiHvIynLYSe1gyQxitlC7ya5Qq3266bnDVx1b21S0CLmjSAQ0w4RpQof0IZTJ0OiLQ8moBNVCcU35GNSsveSd4uTwjWjzBhEq33jfB8/KFor/w9KM5u6am6DuXECRPDZwI7SGv//bmw5GG1K+m1DiXhJsGkimLPMqMRU11MP4RPzBCjv4f0/dy0+U8uAe+2QZMeS3MITB4/EL0b3bVzsZ1zgoR/8V3WT+DbMgc/SEFn0cmUWKnhVsR2fVCWzgX5osZVVtpwyLEKE35Q+9livKYlIrjlnQTAnc1LXMc3yVM/gj3y8wqeR9Z03RecZDgxsraiFoOkFM6H8AwDJARBzuCr8Dw+MxleJxg9H8r0UWXWipEHnzacwGSHRf4Q+uXAzJgbX4uyd1cfoPMx66W5VoauAmFgLicNa1CuziHB7gym52s/nWG1Wd92XiWGOD6WSkjWOq6sI1w9+8ka49xp4AxOegXwk9PO9icFPVnP3SoqG5S1Rn4PC/d2Me8wR1Y56y0FGJhXsu+I="
  bucket: coveo-public-content
  local-dir: dist
  upload-dir: coveo.analytics.js/$TRAVIS_TAG
  acl: public_read
  on:
    tags: true
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ3KKKVUARABLBBDA
  secret_access_key:
    secure: "1QhM57Lhad0fmScPzq/N8BUfaV+8ITG3zc+7R5lqiN92+wKsh2qnU2urLyQKexoOyuhf9HENbwTj55wT5CYU4vhKKxFf6LA364CvvbmHkjuupZpJUCCJtWrm9riCLNG4+rFT86aj+m0VDoqAOJEqua+v8b+fY/ZHfiHvIynLYSe1gyQxitlC7ya5Qq3266bnDVx1b21S0CLmjSAQ0w4RpQof0IZTJ0OiLQ8moBNVCcU35GNSsveSd4uTwjWjzBhEq33jfB8/KFor/w9KM5u6am6DuXECRPDZwI7SGv//bmw5GG1K+m1DiXhJsGkimLPMqMRU11MP4RPzBCjv4f0/dy0+U8uAe+2QZMeS3MITB4/EL0b3bVzsZ1zgoR/8V3WT+DbMgc/SEFn0cmUWKnhVsR2fVCWzgX5osZVVtpwyLEKE35Q+9livKYlIrjlnQTAnc1LXMc3yVM/gj3y8wqeR9Z03RecZDgxsraiFoOkFM6H8AwDJARBzuCr8Dw+MxleJxg9H8r0UWXWipEHnzacwGSHRf4Q+uXAzJgbX4uyd1cfoPMx66W5VoauAmFgLicNa1CuziHB7gym52s/nWG1Wd92XiWGOD6WSkjWOq6sI1w9+8ka49xp4AxOegXwk9PO9icFPVnP3SoqG5S1Rn4PC/d2Me8wR1Y56y0FGJhXsu+I="
  bucket: coveo-public-content
  local-dir: deploy
  upload-dir: coveo.analytics.js
  acl: public_read
  on:
    tags: true
    condition: "$TRAVIS_TAG = latest"
    repo: coveo/coveo.analytics.js
- provider: releases
  skip_cleanup: true
  api_key:
    secure: 4snpEUBznkSWqvhW3GM4wT1hWjFiVMXNlYjhFxn00IXl2Rsr9ABFZo8o6J+b1Kjs+FpnZ5Uyv0zjiZTjNT1yYoRLUZgRW1fLp3zHJqNgweA4iQJMYOMP+7Yxh04JCJOeLVpG93yulszble7D9hDbh75Ptz9XIKHforGLYhhEa1sL3Ajr6fqQRaCtmBWfx5y3mfQfT7JvzptemESQjvC6mK0/7dXBNMKMbFR+3W6tZvhMUJpj9m2TXXP1kLY1I5P2b6UrK5DqPnFy4ZumSjaI3qEoUafMfg6KD9GnnSJYdjWj3MV3EgoxM8ImGqU27V41JaA/B16a6JOo0+WJJQbw5imkE7NlFRDaULX2anMleAWluWxYP5xqov+HPDbqVpizUcQ4gEJyyn9SUnDgCRRMMfQg+iVVahBkbxMMrk7IO/J1BIvUn2DWcIayaMRMuIqusZA95eZZv9a30YVXIgRbLEiJVaBgpHEYAZbftVkIlJZWpQc8VCGA5eM/iMjtBNkoQTIMcnMnKtpNjOZBVkDps5QnGa+/h9RECKlJ7OszrVsc9hhYgV57uW1twZCU1qAut8KtfYS2duotnZPi111rN2+jD7Mcr2RFj8eEsCHMUfD5Xr0mqbYGtmJySyXldmNYBRyFWSYAbFr2xmdw12sV+du/+qGSc8OH9ifjKlHCuBw=
  file:
    - dist/coveoua.js
    - dist/coveoua.js.map
  on:
    tags: true
    repo: coveo/coveo.analytics.js
notifications:
  email:
    on_success: never
    on_failure: never
