sudo: false
language: node_js
node_js:
- stable
env:
  - NODE_ENV=test
before_install:
- source read.version.sh
- echo $PACKAGE_JSON_MAJOR_MINOR_VERSION
install:
- npm install
script:
- npm run build
- npm test
- npm run coveralls
after_success:
- mkdir deploy
- cp dist/coveoua.js dist/coveoua.js.map deploy
deploy:
- provider: npm
  skip_cleanup: true
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: "WJ3Q4PqHx4G+h5RT8Yfy+2Qte5ITwchSHdu8DHMv4c7JzWcEUYmwXlDnLGJtz96koN/gidQZxAQhSb/M2jEFU6+4OoVrUjxEh6Xuc1xUz5M9SfgDXeEW1EbXkY11UvWdetIGDg6Q+3x71q1eLGD377tR/VSc2pplqm0X1Aj8SZgAfUOtd2XLJvv/EbFVNCKXEkXghHdi9MdmWnRA96HP/nrWrMq2Cmde4tZhdY4gMlb2Vv/3xtw5MdUDXk2XjLxNCfU0LwfejF00+7112xbD7jzdCGro2ru63T+WqzWnA5zILLUltQSiH3xl7FMvhCk3i/tiwXQsQJuGtGK1ZW61daxE5tue+DWqUDDqpqoPac4LvoXcprJutpafHwiovY+NY/4tz++cPTiX9odaNDAs4PB7+3/f4WbjmQ7svjZ3u48mD5hCVbVLSCPPgu00NozSBhs3hGvQomoXoruLm2u4EZruVcKMpHzld6RYrYSLtWj4r8nmmYxgkPLk76Z871xh70MvaYdf23mWaDziUFOySt60M5OTlnrdg5CpX+n+qQkLQCs8QGdNDu6x2gNt1OkRc0J7kf4UI747dAsHNo5CLR4bUWZBe/olj2y6l17XhACHUpvwlyrfKS0XC0KRdLrdDqS/DBJfsKlLYh6SLsOFG/BdhpAx5iF7KXvrpEYqKM0="
  on:
    tags: true
    condition: "$TRAVIS_TAG != latest"
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAYKDJLZITS26X53GO
  secret_access_key:
    secure: "qN1Z9yhBkm+tgD4rxzQUQnqpS+agoODn4gazlJ3Rh0WVGe5D91vuMy2Yo6rso1M3A540GLQsamue5wyDsX08Kvi0qREU0LhEB7XKHHP1kToprY8n1uRlmNMQs3tECiHyoyMWZwifaF+N92fqZkmIyaJ2NNdwPcroMEEbVTNRTQ+YC37EawtFlsvD3f1h75ja7G2UyD0PVdg5dNe2qJqpuBN7mviAAqge6ffCqSHHwlTa08QoflazFBFrGBiO/kesV1Xm22ZOR9rc+sH2Q226Bv6EEDzcOgrxR0v4forEbJvFldBPtkReZPfuC7rzJaep1AoLyqYMy/7t2TDyQH3EFHBQkTJwkF1n/jOiWX8KRAvjO1NUxsWc5ZhWRGGJCL7ZYcona8Dw2OLfUdF4lvgPWGki0ooswG6D4gqNl1xmZOvIZWajBu7QffOLkn+Ra1JpbAtZzS4YxYmNn9CehSze/nJIwLnvS6DQ5fKQGz9on0Pb13+Xy474UGr20pEOwGTlmTUzXnEk3dtIaRF+VX36yjpKxjCDOMbpMNa7+6K5GlTX+ncJz46Wg2Xn1GPmEWgL3JBHNUCkaFfX3r4G9UorRQ1HiVJ6poNkbxjT8z4uq71ZKspbzVUVzwOqq/vZza6t5seLScVIaEzPPzJicJixPtQaZmzS0/yogpbet8W/FbA="
  bucket: coveo-public-content
  local-dir: dist
  upload-dir: coveo.analytics.js/$TRAVIS_TAG
  acl: public_read
  on:
    tags: true
    condition: "$TRAVIS_TAG != latest"
    repo: coveo/coveo.analytics.js
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAYKDJLZITS26X53GO
  secret_access_key:
    secure: "qN1Z9yhBkm+tgD4rxzQUQnqpS+agoODn4gazlJ3Rh0WVGe5D91vuMy2Yo6rso1M3A540GLQsamue5wyDsX08Kvi0qREU0LhEB7XKHHP1kToprY8n1uRlmNMQs3tECiHyoyMWZwifaF+N92fqZkmIyaJ2NNdwPcroMEEbVTNRTQ+YC37EawtFlsvD3f1h75ja7G2UyD0PVdg5dNe2qJqpuBN7mviAAqge6ffCqSHHwlTa08QoflazFBFrGBiO/kesV1Xm22ZOR9rc+sH2Q226Bv6EEDzcOgrxR0v4forEbJvFldBPtkReZPfuC7rzJaep1AoLyqYMy/7t2TDyQH3EFHBQkTJwkF1n/jOiWX8KRAvjO1NUxsWc5ZhWRGGJCL7ZYcona8Dw2OLfUdF4lvgPWGki0ooswG6D4gqNl1xmZOvIZWajBu7QffOLkn+Ra1JpbAtZzS4YxYmNn9CehSze/nJIwLnvS6DQ5fKQGz9on0Pb13+Xy474UGr20pEOwGTlmTUzXnEk3dtIaRF+VX36yjpKxjCDOMbpMNa7+6K5GlTX+ncJz46Wg2Xn1GPmEWgL3JBHNUCkaFfX3r4G9UorRQ1HiVJ6poNkbxjT8z4uq71ZKspbzVUVzwOqq/vZza6t5seLScVIaEzPPzJicJixPtQaZmzS0/yogpbet8W/FbA="
  bucket: coveo-public-content
  local-dir: deploy
  upload-dir: coveo.analytics.js/$PACKAGE_JSON_MAJOR_MINOR_VERSION
  acl: public_read
  on:
    tags: true
    condition: "$TRAVIS_TAG = latest"
    repo: coveo/coveo.analytics.js
notifications:
  email:
    on_success: never
    on_failure: never
