name: Build and Test
on:
    pull_request:
        branches: ['master']

permissions:
    contents: read

jobs:
    build-and-test:
        name: 'Build and Test'
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build
              run: npm run build
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Test
              run: npm run test
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
